//main Datos por tipo de visualización

//* Array divide los datos por meses
var alca = [
	{
		alc: "GusA",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 0,
	},
	{
		alc: "Azca",
		trafico: [1, 2, 3, 4, 70],
		aereo: [1, 2, 3, 4, 5, 6, 7, 8],
		maquinaria: [1, 2, 3],
		fiesta: [1, 2, 3, 4],
		bocina: [],
		animal: [1, 2, 3, 4, 5, 6],
		servicios: [1],
		otros: [],
		tReportes: 27,
	},
	{
		alc: "MigH",
		trafico: [1, 2, 3, 4, 5, 6],
		aereo: [],
		maquinaria: [],
		fiesta: [],
		bocina: [1],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 0,
	},
	{
		alc: "Cuau",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 0,
	},
	{
		alc: "VenC",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 0,
	},
	{
		alc: "CuaM",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [1, 2],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 2,
	},
	{
		alc: "AlvO",
		trafico: [1, 2],
		aereo: [],
		maquinaria: [1],
		fiesta: [],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 3,
	},
	{
		alc: "BenJ",
		trafico: [1, 2, 3, 4],
		aereo: [1],
		maquinaria: [],
		fiesta: [1, 2],
		bocina: [1, 2, 3],
		animal: [],
		servicios: [],
		otros: [1, 2, 3],
		tReportes: 13,
	},
	{
		alc: "Izta",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 0,
	},
	{
		alc: "Coyo",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [1],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 1,
	},
	{
		alc: "Iztp",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 0,
	},
	{
		alc: "MagC",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 0,
	},
	{
		alc: "Tlal",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 0,
	},
	{
		alc: "Xoch",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 0,
	},
	{
		alc: "Tlah",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 0,
	},
	{
		alc: "Milp",
		trafico: [],
		aereo: [],
		maquinaria: [],
		fiesta: [],
		bocina: [],
		animal: [],
		servicios: [],
		otros: [],
		tReportes: 0,
	},
];

/* var presion = [
	{ rango: "30_39", color: "#7CE0FF", colorT: "#7CE0FF80", valor:2, data: [36,37] },
	{ rango: "40_49", color: "#89D0FF", colorT: "#89D0FF80", valor:14, data: [40,41,41,42,42,42,42,44,45,46,46,47,47,48] },
	{ rango: "50_59", color: "#B4BAFF", colorT: "#B4BAFF80", valor:11, data:[52,53,53,53,54,54,56,58,58,58,59] },
	{ rango: "60_69", color: "#E1A0EA", colorT: "#E1A0EA80", valor:7, data: [62,63,63,65,66,67,68] },
	{ rango: "70_79", color: "#FE87B8", colorT: "#FE87B880", valor:15, data: [70,72,73,73,73,74,74,74,74,74,74,74,75,77,79] },
	{ rango: "80_89", color: "#FF7C7C", colorT: "#FF7C7C80", valor:1, data: [83] },
]; */
